using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CodeGenerator;

public abstract class JsonMappingGenerator : IIncrementalGenerator {

    protected abstract string TargetType { get; }
    protected abstract string BaseNameSpace { get; }

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var classDeclarations = context.SyntaxProvider.CreateSyntaxProvider(
           predicate: static (s, _) => s is ClassDeclarationSyntax,
           transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node
        );

        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndClasses, (spc, source) => RenderAttribute(source.Left, source.Right, spc));
    }

    private void RenderAttribute(Compilation compilation, ImmutableArray<ClassDeclarationSyntax> classes, SourceProductionContext context) {
	    if (classes.IsDefaultOrEmpty) return;

	    List<INamedTypeSymbol> derivedTypes = [];

	    foreach (var classSyntax in classes) {
		    var semanticModel = compilation.GetSemanticModel(classSyntax.SyntaxTree);
		    if (semanticModel.GetDeclaredSymbol(classSyntax) is not { } classSymbol) continue;

		    if (InheritsFrom(classSymbol, TargetType)) {
			    derivedTypes.Add(classSymbol);
		    }
	    }

	    var sb = new StringBuilder();
	    sb.AppendLine($"""
			// <auto-generated />
			using System.Text.Json.Serialization;

			namespace {BaseNameSpace};

			[JsonPolymorphic(TypeDiscriminatorPropertyName = "$type")]
			"""
	    );

	    foreach (var derivedType in derivedTypes) {
		    sb.AppendLine($"[JsonDerivedType(typeof({derivedType.Name}), \"{derivedType.Name}\")]");
	    }

	    sb.AppendLine($"public abstract unsafe partial class {TargetType}" + " { }");

	    context.AddSource($"{TargetType}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static bool InheritsFrom(INamedTypeSymbol type, string baseTypeName) {
	    var current = type.BaseType;

	    while (current != null) {
		    if (current.Name == baseTypeName) return true;
		    current = current.BaseType;
	    }

	    return false;
    }
}